Algoritmo "cadastro_de_funcionarios2"

Var

nome, funca, idade, sexo: caracter
salario: real
list, i: inteiro

Inicio
escreval("informe dados do funcionário na seguinte ordem:")
escreval("Nome")
escreval("Função")
escreval("Idade")
escreval("Sexo")
escreval("Salário")

para i de 0 ate 4 faca

escreval("Dados funcionário ", i+1)
leia(nome)
leia(funca)
leia(idade)
leia(sexo)
leia(salario)

fimpara
Fimalgoritmo